platform :ios, '8.0'
inhibit_all_warnings!

target 'LKProject' do
  pod 'AFNetworking', '~> 3.0'               # 网络请求
#  pod 'YYWebImage'                           # 图片缓存
  pod 'YYModel'                              # 数据转模型
  pod 'Toast', '~> 3.0'                      # 提示窗
  pod 'MBProgressHUD', '~> 0.9.2'            # 提示框
#  pod 'RMUniversalAlert'                     # Alert ActionSheet
#  pod 'TZImagePickerController', '~> 1.7.8'  # 图片选择器
#  pod 'KLCPopup'                             # 弹出动画
#  pod 'Masonry', '~> 1.0.2'                  # 适配
#  pod 'MWPhotoBrowser', :git => 'https://git.oschina.net/YuriZhang/MWPhotoBrowser.git'    # 图片浏览器
#
#  pod 'ActionSheetPicker-3.0', '~> 2.2.0'    # picker ActionSheet
#  pod 'IQKeyboardManager'                    # 键盘管理
#  pod 'MGSwipeTableCell'                     # 侧滑
end
